### ISSUE TITLE
Killbox Score Issue

### ISSUE THREAD

**Issue by Rexuiem** [Rexuiem/PlatformPanicGame#10]
**Killbox Score Issue**

When a player hits the killbox, their "score" decreases by two rather than one.

**Version 010**

**To Reproduce**

1. Open the scene. 
2. Press the 'play' button.
3. Have player one jump off the level
4. Check player ones score stat on the player one inspector.

**Expected Behaviour**

The player's score should be decreased by one upon hitting the killbox.

**Desktop System**

Windows 10

**Comment by Metablu** [comment]
Obsolete as we are using a stock system instead of a score system.
