### ISSUE TITLE
Clinging to Platforms Bug

### ISSUE THREAD

**Issue by Rexuiem** [Rexuiem/PlatformPanicGame#11]
**Clinging to Platforms Bug**

When a player hits the side of a platform, and presses in the direction of the platform, they will cling to it indefinitely.

**Version 010**

**To Reproduce**

1. Open the scene. 
2. Press the 'play' button.
3. Have player one jump and hit the side of a platform
3. Have player one either hold A if the platform is to the left, or D if the platform is to the right.

**Expected Behaviour**

Player one should slide off the side of the platform, and be unable to jump again.

**Desktop System**

Windows 10

**Comment by Metablu** [comment]
After playtesting we've decided that this is an entertaining feature that we wish to keep.
