### ISSUE TITLE
Score Tracking Issue

### ISSUE THREAD

**Issue by Rexuiem** [Rexuiem/PlatformPanicGame#15]
**Score Tracking Issue**

No matter which player dies, only player two's score will increase, even if player two dies.

**Version 018**

**To Reproduce**

1. Open the scene. 
2. Press the 'play' button.
3. Have player one jump off a platform, and exit the screen from the bottom.
4. Look at the "Score" at the top of the scene.
5. Have player two jump off a platform, and exit the scene from the bottom.
6. Look at the "Score" at the top of the screen.

**Expected Behaviour**

When player one dies, the right score should be updated. When player two dies, the left score should be updated.

**Desktop System**

Windows 10

**Comment by Metablu** [comment]
Obsolete as we are using a stock system instead of a scoring system.
