### ISSUE TITLE
Infinite Healing/Damage Bug

### ISSUE THREAD

**Issue by Rexuiem** [Rexuiem/PlatformPanicGame#9]
**Infinite Healing/Damage Bug**

When the fire or healing effect is applied to a platform and a player enters the effect, their health value does not stop changing until the player jumps, even if the effect is no longer applied to the playform

**Version 010**

**To Reproduce**

1. Open the scene. 
2. Press the 'play' button.
3. Have player two stand on a platform
3. Have player one hit player two's platform with either the healing or fire ability.
4. Have player two stand without jumping.

**Expected Behaviour**

Player two should stop healing/taking damage when the effect ends on the platform.

**Desktop System**

Windows 10

**Comment by Metablu** [comment]
Bug was fixed on the 30/09/2019.
